### ISSUE TITLE
Error uploading big files

### ISSUE THREAD

**Issue by AllTernative90** [fkalis/bash-onedrive-upload#14]
Hi,

thanks for this awesome tool! I got it working with smaller files (500 MB worked fine too). Now I want to upload larger files, the one in question is 4.4 GB. But I'm getting an unauthorized response. This only happens with large files. Any idea?
I am using the larger-files version of your tool.
Log is attached.
[uploader.txt](https://github.com/fkalis/bash-onedrive-upload/files/52802/uploader.txt)

**Comment by fkalis** [comment]
How long does the upload take?

I did not experiment with that large files, but maybe the upload session expires during uploading. I did not yet take a look at the "expirationDateTime" of the upload url.

The file size shouldn't be a problem. As far as I know, you should be able to upload files up to [10 GiB via the REST-API](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/6692867-remove-or-document-rest-api-limits-throttling).

**Comment by AllTernative90** [comment]
The Upload took exactly one hour. After one hour I got the attached log.
I suppose it could be a fault of the "at" program which I used to schedule the upload. Maybe jobs in "at" get aborted after 1 hour processing time. The upload would've taken several hours.
I'll look into that and get back to you.

**Comment by fkalis** [comment]
I don't think `at` terminates your processes. It seems more likely that the server responded with a wrong status code during the upload of one chunk. Since I haven't implemented #8 yet (neither for simple nor for chunked uploads), the script will then terminate the upload session.

Can you retry the upload with the `-d` option (enables debug messages)?

**Comment by AllTernative90** [comment]
Since I cannot take up my whole bandwith right now, I'll retry the upload later and attach the log tomorrow. Thanks for you support!

**Comment by fkalis** [comment]
I tried to reproduce the error. After about 700 MiB of successfully transferred data, I receive the following exception from the cURL process:

>  SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054

This happened after transferrering 7 MiB of the current chunk.

**Comment by fkalis** [comment]
I have narrowed the problem down to the expiration of the access_token: After exactly one hour of uploading chunks to the same upload_url provided by the upload session, the upload fails with an error 401. A closer look at the upload_url shows, that it contains the access_token.

The solution to this problem is easy: I have to strip the access_token from the upload_url and manually add the access_token for each upload. This way I can update the access_token between two chunks if necessary.

**Comment by AllTernative90** [comment]
Alright, thank you for looking into this issue! I'll be waiting for a fix then, thanks!

**Comment by fkalis** [comment]
The access_token issue is fixed now. Please try again.

**Comment by AllTernative90** [comment]
Somehow the authorization fails now...
Any ideas? Am I doing something wrong?

[api-error.txt](https://github.com/fkalis/bash-onedrive-upload/files/52982/api-error.txt)

**Comment by AllTernative90** [comment]
I can confirm this, my upload worked. Thank you!
