### ISSUE TITLE
problems with auth

### ISSUE THREAD

**Issue by physikerwelt** [fkalis/bash-onedrive-upload#23]
I followed the install instructions, installed curl, set up a new application, and entered the code to the .cfg file
I can navigate to the link and see the new application in my [microsoft account permission page](https://account.live.com/consent/Manage).
However the auth script returns an error message:
```
~/bash-onedrive-upload$ ./onedrive-authorize
Please open the following URL in your browser and follow the steps until you see a blank page:
https://login.live.com/oauth20_authorize.srf?client_id=00000000XXXX&scope=wl.offline_access%20onedrive.readwrite&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

When ready, please enter the value of the code parameter (from the URL of the blank page) and press return
 
Something went wrong, here is the API response:
{"error":"invalid_request","error_description":"The provided request must include a 'code' input parameter."}
```

**Comment by fkalis** [comment]
Did you `enter the value of the code parameter (from the URL of the blank page)`?

When you see the blank page you have to copy a part of the URL and enter it in the script.

The `error_description` suggests that the entered `code` was empty.

You can see the new application in your account permission page because the permission was granted, but the script does not (yet) know about that without the code (which is required to acquire an access_token).

**Comment by physikerwelt** [comment]
Reading helps. Sorry for this stupid question.
