### ISSUE TITLE
Recursive uploads

### ISSUE THREAD

**Issue by trufanov-nok** [fkalis/bash-onedrive-upload#25]
Hi,
Would be great if tool will be able to upload a folder and its subfolders recursively and automatically creating remote folders.
Like `cp folder_name target_folder_name` copies  a folder with all subfolders and files in them to a new destination.

**Comment by fkalis** [comment]
Thank you for your suggestion. As soon as I find the time, I will look into that.

**Comment by Tomto23** [comment]
That feature would be very helpful for me, too.

**Comment by diman82** [comment]
Any new regarding this one?
I think recursive upload (preserving folder structure) is crucial.

**Comment by fkalis** [comment]
I didn't have the time yet, but I think you can expect this feature to be implemented sometime in July.

**Comment by fkalis** [comment]
Sorry for the delay, but finally I have found the time to start implementing this feature.

To avoid concurrency problems, the script will first traverse through the local filesystem and create the needed folder structure in OneDrive, collecting a list of pairs (destination folder ids and filenames) before starting the actual multi-threaded upload.

To minimize the number of requests for the initial folder traversal, the function `resolve_folder_id` must work relative to the current directory rather than evaluating the same path prefix over and over again. For now this process can take quite a while even for small structures, especially when used with the command line option `-f` in combination with a long path.

**Comment by trufanov-nok** [comment]
Great! Will test tomorrow.

**Comment by trufanov-nok** [comment]
Hi, Have finally tested it. (took several minutes to realize that functionality is still in separate branch). It works fine as expected. Thank you one more time!

**Comment by shoeper** [comment]
Am also going to test it with several 100 GiB of data on thursday.
